# -*- coding: utf-8 -*-
"""Submission 2-Muhammad Faris Akbar-MLT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDN-ixzd4vsCKC8WvGTbBZhNRk3Cz8rG

# **Sistem Rekomendasi Content Based Filtering: Jurnal ArXiv**

# **Import Library**
Pada tahapan awal, lakukan import library yang akan digunakan dan akses env variable dari google collab untuk akses ke eksternal source yang lebih mudah (Hugging Face, Kaggle)
"""

import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json
import gc
import re
import nltk
import torch

from tqdm.auto import tqdm
from sentence_transformers import SentenceTransformer
from text_unidecode import unidecode
from google.colab import userdata
from huggingface_hub import login

from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

# Retrieve the token safely from your secrets vault
hf_token = userdata.get('HF_TOKEN')

# Log in to the Hugging Face Hub
login(hf_token)

"""# **Download Dataset dari Kaggle ([Dataset](https://www.kaggle.com/datasets/Cornell-University/arxiv/data))**
Download dataset dari kaggle, setelahnya mengecek list nama file yang terdapat pada folder download untuk dilakukan validasi file
"""

# Download latest version
path = kagglehub.dataset_download("Cornell-University/arxiv")

print("Path to dataset files:", path)

for f in os.listdir(path):
  print(f)

"""## **Contoh Isi Dataset Yang Sudah Didownload**

```
{
  "id": "0704.0001",
  "submitter": "Pavel Nadolsky",
  "authors": "C. Bal'azs, E. L. Berger, P. M. Nadolsky, C.-P. Yuan",
  "title": "Calculation of prompt diphoton production cross sections at Tevatron and\n  LHC energies",
  "comments": "37 pages, 15 figures; published version",
  "journal-ref": "Phys.Rev.D76:013009,2007",
  "doi": "10.1103/PhysRevD.76.013009",
  "report-no": "ANL-HEP-PR-07-12",
  "categories": "hep-ph",
  "license": null,
  "abstract": "  A fully differential calculation in perturbative quantum chromodynamics is\npresented for the production of massive photon pairs at hadron colliders. All\nnext-to-leading order perturbative contributions from quark-antiquark,\ngluon-(anti)quark, and gluon-gluon subprocesses are included, as well as\nall-orders resummation of initial-state gluon radiation valid at\nnext-to-next-to-leading logarithmic accuracy. The region of phase space is\nspecified in which the calculation is most reliable. Good agreement is\ndemonstrated with data from the Fermilab Tevatron, and predictions are made for\nmore detailed tests with CDF and DO data. Predictions are shown for\ndistributions of diphoton pairs produced at the energy of the Large Hadron\nCollider (LHC). Distributions of the diphoton pairs from the decay of a Higgs\nboson are contrasted with those produced from QCD processes at the LHC, showing\nthat enhanced sensitivity to the signal can be obtained with judicious\nselection of events.\n",
  "versions": [
    {
      "version": "v1",
      "created": "Mon, 2 Apr 2007 19:18:42 GMT"
    },
    {
      "version": "v2",
      "created": "Tue, 24 Jul 2007 20:10:27 GMT"
    }
  ],
  "update_date": "2008-11-26",
  "authors_parsed": [
    [
      "Balázs",
      "C.",
      ""
    ],
    [
      "Berger",
      "E. L.",
      ""
    ],
    [
      "Nadolsky",
      "P. M.",
      ""
    ],
    [
      "Yuan",
      "C. -P.",
      ""
    ]
  ]
}
```

Dari total 14 kolom yang terdapat pada data JSON tersebut, hanya digunakan 5 kolom untuk sistem rekomendasi yaitu:

1. Authors
2. Title
3. Categories
4. Abstract
5. Update_date

Hal tersebut dikarenakan beberapa kolom lainnya seperti doi, version, id dan lainnya, tidak terlalu relevan untuk dijadikan parameter dalam sistem rekomendasi

## **Function Section Untuk Akses Data**
Membuat function untuk load dataset besar agar tidak menghabiskan banyak ram (1 baris per 1 pemanggilan).
"""

def get_data(file_path):
  with open(file_path) as f:
    for line in f:
       yield json.loads(line)

"""Pembuatan function load_data untuk membaca dictionary dari return get_data menjadi dataframe. Sebagai tambahan, dilakukan parsing data dengan menambahkan tahun yang bertindak sebagai filter pada data."""

file_path = os.path.join(path, "arxiv-metadata-oai-snapshot.json")

def load_data(file_path, start_year=None, end_year=None):
  """
  Function untuk load data dari file JSON, jika start_year==None dan end_year=None maka akan load semua data, jika tidak maka akan load data dari tahun yang ditentukan
  input: file_path, start_year, end_year
  return: dataframe
  """
  generator_data = get_data(file_path)

  dataframe = {
    'authors': [],
    'title': [],
    'categories': [],
    'abstract': [],
    'update_date': [],
    'year': [],
    'month': []
  }

  for paper in generator_data:
    try:
      year_date = int(paper['update_date'].split('-')[0])
      month_date = int(paper['update_date'].split('-')[1])
      is_valid = False

      # 1. Jika kedua filter kosong, semua data lolos
      if start_year is None and end_year is None:
          is_valid = True

      # 2. Jika ada rentang tahun (dua-duanya diisi)
      elif start_year is not None and end_year is not None:
          if start_year <= year_date <= end_year:
              is_valid = True

      # 3. Jika hanya end_year yang diisi (start_year kosong)
      elif start_year is None and end_year is not None:
          if year_date <= end_year:
              is_valid = True

      # 4. Jika hanya start_year yang diisi (end_year kosong)
      elif start_year is not None and end_year is None:
          if start_year <= year_date:
              is_valid = True

      # Jika lolos filter, masukkan ke storage
      if is_valid:
        dataframe['authors'].append(paper.get('authors', ''))
        dataframe['title'].append(paper.get('title', ''))
        dataframe['categories'].append(paper.get('categories', ''))
        dataframe['abstract'].append(paper.get('abstract', ''))
        dataframe['update_date'].append(paper.get('update_date', ''))
        dataframe['year'].append(year_date)
        dataframe['month'].append(month_date)

    except (KeyError, ValueError, IndexError):
      continue
      # Mengantisipasi jika ada baris data yang rusak atau format tanggal salah

  del generator_data
  gc.collect()

  return pd.DataFrame(dataframe)

"""## **Akses Data**
Implementasikan load_data untuk mengakses file yang sudah didownload, kemudian tampilkan 5 data teratas dan terbawah untuk validasi function.
"""

df = load_data(file_path, start_year=2026, end_year=None)

df.head(5)

df.tail(5)

"""Cek tahun yang terdapat pada dataset untuk memastikan bahwa filter sudah berjalan dengan benar"""

df['year'].unique()

"""Cek informasi dan deskripsi dari dataset, memastikan bahwa tidak ada kesalahan type data maupun persebaran data"""

df.info()

"""# **Exploratory Data Analysis**

Exploratory Data Analysis Dilakukan Untuk Menganalisis Informasi Yang Terdapat Pada Data, dimana tahapan EDA ini bisa dilakukan lebih dari 1x tergantung pada kondisi pada dataset.

## **Function Section Untuk EDA**
Section yang berfokuskan pada eksplorasi dan analisis data untuk preprocessing, seperti mencari nilai nan dan duplikat
"""

def cek_nan(data):
  """
  Function yang digunakan untuk memeriksa nilai nan dari data
  input   : data
  output  : nan_info (DataFrame)
  return  : nan_info (DataFrame)
  """
  nan_info = pd.DataFrame(data.isna().sum().sort_values(ascending=False), columns=['Jumlah Nilai Missing'])

  if nan_info['Jumlah Nilai Missing'].sum() == 0:
    print("Tidak ada nilai missing")
    return None
  else:
    nan_info['Persentase Nilai Missing (%)'] = ((nan_info['Jumlah Nilai Missing'] / len(data)) * 100).round(3)

    # return data dengan nilai missing, apabila ingin mereturn keseluruhan data maka ubah menjadi return nan_info
    return nan_info[nan_info['Jumlah Nilai Missing'] > 0]


def visualize_row_with_nan(data, method='all', columns=None):
  """
  Procedure yang digunakan untuk menvisualisasikan baris yang mengandung NaN berdasarkan metode yang dipilih
  input   : data, method, columns
  output  : baris_nan (DataFrame)
  """
  try:
    if method not in ['all', 'column', 'columns']:
      raise ValueError("Metode tidak valid. Pilih salah satu dari 'all', 'column', 'columns'.")

    if method == 'all':
      display(data[data.isna().any(axis=1)])

    elif method == 'column':
      if not isinstance(columns, str):
          raise TypeError("Untuk metode 'column', argumen 'columns' harus berupa String.")
      if columns not in data.columns:
          raise KeyError(f"Kolom '{columns}' tidak ditemukan dalam DataFrame.")
      display(data[data[columns].isna()])

    elif method == 'columns':
      if not isinstance(columns, list):
          raise TypeError("Untuk metode 'columns', argumen 'columns' harus berupa list.")
      for column in columns:
          if column not in data.columns:
              raise KeyError(f"Kolom '{column}' tidak ditemukan dalam DataFrame.")
      display(data[data[columns].isna().all(axis=1)])

  except (TypeError, KeyError) as e:
    print(f"Kesalahan dalam memproses data: {e}")


def visualize_row_with_duplicated(data, column=None):
  """
  Procedure yang digunakan untuk menvisualisasikan baris yang mengandung data duplikat
  input   : data
  output  : baris_duplikat (DataFrame)
  """
  duplicated_count = data.duplicated(subset=column).sum()

  if duplicated_count > 0:
    print("Jumlah Data Duplikat :", duplicated_count)
    all_duplicates = data[data.duplicated(subset=column, keep=False)]

    if column is None:
      duplicate_indices = all_duplicates.groupby(list(all_duplicates.columns)).groups
    else:
      duplicate_indices = all_duplicates.groupby(column).groups

    print("Pasangan Data Duplikat :")
    for group_indices in duplicate_indices.values():
      if len(group_indices) > 1:
        display(data.iloc[list(group_indices)])
        print("\n")
  else:
    print("Tidak ada data duplikat")

"""## **Function Section Untuk Pre-Processing**
Section yang difokuskan untuk pre-processing data teks, dengan fokus pada case folding serta regex untuk membersihkan simbol, logo, latex, dan sebagainya
"""

lemmatizer = WordNetLemmatizer()

def lower_case(data):
  """Case Folding. Mengecilkan huruf agar seragam"""
  data = data.str.lower()
  return data

def pembersihan_dasar(teks):
  """Hanya menangani unidecode dan spasi ganda. Aman untuk SEMUA kolom."""
  teks = unidecode(teks)
  teks = re.sub(r'\s+', ' ', teks).strip()
  return teks

def bersihkan_categories(teks):
  """
  Mengubah format spasi antar kategori menjadi dipisahkan oleh koma.
  Contoh: 'math.na cs.na' -> 'math.na, cs.na'
  """
  if not isinstance(teks, str):
    return teks

  # Mengganti spasi (baik satu maupun lebih) di tengah teks dengan koma + spasi
  teks = re.sub(r'\s+', ', ', teks.strip())

  # Kembalikan ke pembersihan dasar untuk merapikan sisa spasi & unidecode
  return pembersihan_dasar(teks)

def bersihkan_title(teks):
  """
  Khusus membersihkan judul dari simbol matematika LaTeX
  """
  if not isinstance(teks, str):
    return teks

  # 1. Hilangkan tanda subscript (_)
  teks = re.sub(r'_', ' ', teks)

  # 2. Hilangkan kurung kurawal penanda grup LaTeX { } dan beberapa simbol
  teks = re.sub(r'[\{\}\_\^\$\\\"]', '', teks)

  return pembersihan_dasar(teks)

def bersihkan_author(teks):
  """Khusus menghapus afiliasi dan indeks angka."""
  # 1. Hapus catatan kaki institusi kompleks di paling ujung jika ada format ((1) ...)
  teks = re.sub(r'\s*\(\s*\([0-9]+\).*$', '', teks)

  # 2. Hapus semua jenis kurung berisi afiliasi teks maupun angka
  # Pola [^)]+ artinya menghapus apa pun di dalam kurung selama itu bukan kurung tutup
  teks = re.sub(r'\s*\([^)]+\)', '', teks)

  # 3. Bersihkan aksen LaTeX standar seperti \'e -> e, \`a -> a
  teks = re.sub(r"\\[\'\"\`\^~]([a-zA-Z])", r"\1", teks)

  # 4. Bersihkan aksen LaTeX Cedilla seperti \c{c} -> c
  # Pola ini mencari \c{ dilanjutkan huruf, lalu ditutup }
  teks = re.sub(r"\\[cv]\{([a-zA-Z]+)\}", r"\1", teks)

  # 5. Bersihkan karakter spesial LaTeX di dalam kurung kurawal seperti {\l} -> l
  # Pola ini mencari '{' diikuti '\' dan satu huruf, lalu ditutup dengan '}'
  teks = re.sub(r"\{\\([a-zA-Z])[a-zA-Z]*\}", r"\1", teks)

  return pembersihan_dasar(teks)

def bersihkan_abstract(teks):
  """Khusus menangani LaTeX dan rumus matematika."""
  teks = re.sub(r"\\[\'\"\`\^~]([a-zA-Z])", r"\1", teks) # Kollar
  teks = re.sub(r'\s*:=\s*', ' ', teks) # Operator :=
  teks = re.sub(r'[\{\}\$\_\\]', '', teks) # Hilangkan kurung kurawal penanda grup { } dan beberapa simbol

  return pembersihan_dasar(teks)


def preprocessing_khusus_tfidf(teks):
  """
  Fungsi ini khusus untuk mengubah kata menjadi bentuk dasarnya (Lemmatization).
  Hanya digunakan untuk pendekatan TF-IDF, BUKAN untuk Sentence Transformers.
  """
  if not isinstance(teks, str):
    return teks

  # Memecah kalimat menjadi list kata (Tokenisasi)
  tokens = word_tokenize(teks)

  # Mengubah setiap kata ke bentuk dasar (misal: "images" -> "image", "learning" -> "learn")
  teks_lemmatized = " ".join([lemmatizer.lemmatize(kata) for kata in tokens if kata.isalnum()])

  return teks_lemmatized

"""## **Case Folding**
Implementasi function lower_case untuk memastikan bahwa data sudah seragam dan menghindari terdapatnya data yang sama namun penulisan nya berbeda sehingga tidak terdeteksi duplikat.
"""

df['authors'] = lower_case(df['authors'])
df['title'] = lower_case(df['title'])
df['categories'] = lower_case(df['categories'])
df['abstract'] = lower_case(df['abstract'])

"""## **Cek Kolom NaN dan Duplikat**

Implementasi function cek_nan untuk memastikan bahwa tidak ada nilai yang kosong pada dataset.
"""

cek_nan(df)

"""Mengimplemenasikan procedure visualize_row_with_duplicated untuk memeriksa data duplikat dalam dataset serta menampilkan baris datanya"""

visualize_row_with_duplicated(df, column=None)

"""Dari total 237226 data, terdapat 1 data yang merupakan duplikat. Namun jika diperhatikan, kolom update_date sebenarnya sudah tidak diperlukan karena kita sudah memiliki kolom year dan month yang didapatkan melalui ekstraksi kolom update_date, sehingga kita akan melakukan validasi ulang dahulu tanpa kolom update_date, untuk memastikan bahwa data sudah benar tidak memiliki duplikat"""

df.drop('update_date', axis=1, inplace=True)

"""Implementasikan ulang procedure visualize_row_with_duplicated untuk memastikan bahwa data sudah benar bersih dari duplikat dan tidak ada duplikat yang dikarenakan kolom update_date maupun error data, tapi sebelum itu, perlu diingat bahwa month juga bersumber dari update_date dan ada kemungkinan bahwa 1 paper diupdate beberapa kali dalam bulan yang sama, sehingga lebih baik pada pemeriksaan duplikat selanjutnya, digunakan subset kolom untuk pemeriksaan nya."""

subset_columns = ['authors', 'title', 'categories', 'abstract']

visualize_row_with_duplicated(df, column=subset_columns)

"""Ternyata hipotesis tersebut benar, dari 237226 terdapat 2 data tambahan yang merupakan duplikat karena berasal dari update_date sehingga total data duplikat sebanyak 3. Sehingga selanjutnya, kita bisa langsung melanjutkan tahapan dengan drop data duplikat dan reset index dari awal"""

df.drop_duplicates(subset=subset_columns, keep='first', inplace=True)
df.reset_index(drop=True, inplace=True)

"""Cek ulang informasi dan jumlah data pada dataset untuk memastikan bahwa penghapusan nilai duplikat sudah berhasil serta tidak ada error selama proses berjalan"""

df.info()

"""Cek 5 kolom teratas dan terbawah untuk validasi function"""

df.head(5)

df.tail(5)

"""# **Pre-Processing Teks**
Implementasikan function preprocessing untuk masing-masing kolom kecuali year, untuk categories hanya dilakukan pembersihan dasar untuk menghilangkan spasi berlebih dan unicode serta penambahan (,). Disimpan dalam dataframe baru agar data lama tidak hilang
"""

tqdm.pandas(desc="Proses Pre-Processing Teks")

df_preprocessed = df.assign(
    authors=df['authors'].progress_apply(bersihkan_author),
    title=df['title'].progress_apply(bersihkan_title),
    categories=df['categories'].progress_apply(bersihkan_categories),
    abstract=df['abstract'].progress_apply(bersihkan_abstract),
    year=df['year'],
    month=df['month']
)

"""Cek 5 kolom teratas dan terbawah untuk validasi function"""

df_preprocessed.head(5)

df_preprocessed.tail(5)

"""## **Explarotory Data Analysis Setelah Pre-Processing**

### **Top 10 Kategori Terbanyak Dalam Data**
"""

count_top_10_categories = df_preprocessed['categories'].str.split(', ', expand=True).stack().value_counts().head(10)
count_top_10_categories

plt.figure(figsize=(10, 6))
ax = sns.barplot(x=count_top_10_categories.index, y=count_top_10_categories.values, palette='viridis')
plt.title('Top 10 Kategori Terbanyak')
plt.xlabel('Kategori')
plt.ylabel('Jumlah Artikel')
for p in ax.patches:
    ax.annotate(f'{p.get_height():.0f}', (p.get_x() + p.get_width() / 2, p.get_height()), # p.get_x(): Koordinat x atau titik kiri batang, p.get_width() / 2: Lebar batang / 2, p.get_height(): Koordinat y
                ha='center', va='center', xytext=(0, 5), textcoords='offset points')
plt.show()

"""### **Proporsi Angka Terbit Perbulan**"""

count_monthly_publication = df_preprocessed['month'].value_counts().sort_index()
count_monthly_publication

plt.figure(figsize=(10, 6))
ax = sns.barplot(x=count_monthly_publication.index, y=count_monthly_publication.values, palette='viridis')
plt.title('Proporsi Angka Terbit Perbulan')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Artikel')

for p in ax.patches:
    ax.annotate(f'{p.get_height():.0f}', (p.get_x() + p.get_width() / 2, p.get_height()), # p.get_x(): Koordinat x atau titik kiri batang, p.get_width() / 2: Lebar batang / 2, p.get_height(): Koordinat y
                ha='center', va='center', xytext=(0, 5), textcoords='offset points')
plt.show()

"""# **Feature Engineering**
Buat kolom untuk mengkombinasikan teks title dan abstract, digunakan untuk melatih model pre-trained embedding sehingga dapat mengakses makna semantik yang lebih kaya pada ruang vektor. Pemilihan 2 kolom ini dikarenakan 2 kolom ini memiliki besaran kata paling banyak dibandingkan year, author, maupun categories, sehingga jika year, author, maupun categories dimasukkan dalam model embedding, maka kemungkinan besar 3 kolom tersebut tidak akan berpengaruh signifikan karena mayoritas vektor berasal dari title dan abstract
"""

df_preprocessed['combined_text'] = (
    "title: " + df_preprocessed['title'] + ". " +
    "abstract: " + df_preprocessed['abstract']
)

"""Cek 5 kolom teratas dan terbawah untuk validasi feature"""

df_preprocessed.head(5)

df_preprocessed.tail(5)

"""## **Pre-Processing Tambahan Untuk Model TF-IDF**
Mengimplementasikan function preprocessing khusus model TF-IDF serta penghapusan stop word.
"""

tqdm.pandas(desc="Proses Pre-Processing Teks TF-IDF")
df_preprocessed['combined_text_tfidf'] = df_preprocessed['combined_text'].progress_apply(preprocessing_khusus_tfidf)

"""Cek 5 kolom teratas dan terbawah untuk validasi feature"""

df_preprocessed.head(5)

df_preprocessed.tail(5)

"""# **Ekstraksi Teks**
Tahapan ekstraksi informasi semantik pada teks ke dalam representasi angka

## **TF-IDF Vectorizer**
Mengisialisasi model ekstraksi teks ke angka yang memanfaatkan bag of word atau jumlah kata pada suatu dokumen
"""

# Gunakan stop_words='english' untuk membuang kata hubung
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=10000, min_df=5, max_df=0.8)

# Masukkan kolom yang sudah di-lemmatize
tfidf_matrix = tfidf_vectorizer.fit_transform(df_preprocessed['combined_text_tfidf'])

"""## **Model Pre-Trained Embedding**
Menginisialisasi model embedding transformer untuk dapat mengekstrak makna semantik dari teks ke dalam representasi ruang vektor.
"""

model = SentenceTransformer('all-MiniLM-L6-v2', device=device)
# model = SentenceTransformer('sentence-transformers/allenai-specter', device=device)
embeddings = model.encode(df_preprocessed['combined_text'].tolist(), batch_size=64, show_progress_bar=True)

"""# **Model Pengelompokkan Untuk Mencari Kelompok Data Yang Memiliki Kedekatan Semantik**

## **Nearest Neighbors**
Menginisialisasi model NearestNeighbors sebagai model pengelompokkan data, dengan detail parameter:

1.   n_neigbors: Jumlah tetangga terdekat dengan data, termasuk data input menjadi n+1
2.   metric: Perhitungan jarak kedekatan pada data, pada kode ini digunakan 'cosine' yang artinya menggunakan pendekatan cosine distance pada data
3. algorithm: Pemilihan algoritma pada model, dapat disesuaikan dengan data atau biarkan sebagai default ('auto')
"""

nn_model = NearestNeighbors(n_neighbors=6, metric='cosine', algorithm='auto')
nn_model.fit(embeddings)

"""# **Function Section Rekomendasi Berdasarkan Query**
Section yang difokuskan untuk menganalisis query dengan dataset, dengan mengambil top_n sebagai jumlah rekomendasi nya
"""

def get_recommendations_by_query(query_text, top_n=5):
    """
    Memberikan rekomendasi artikel berdasarkan input teks bebas.
    """
    # 1. Ubah query teks menjadi vektor menggunakan model NLP yang sudah di-load
    target_vector = model.encode([query_text])

    # 2. Cari tetangga terdekat.
    distances, indices = nn_model.kneighbors(target_vector, n_neighbors=top_n)

    # 3. Ambil seluruh indeks dari hasil pencarian
    recommended_indices = indices[0]

    print(f"Rekomendasi untuk pencarian: '{query_text}'")

    # 4. Kembalikan data dari dataframe
    return df_preprocessed.iloc[recommended_indices][['title', 'authors', 'categories', 'abstract', 'year']]

def get_recommendations_tfidf(query_text, top_n=5):
    """
    Memberikan rekomendasi artikel menggunakan TF-IDF dan Cosine Similarity.
    """
    # print(f"Mencari rekomendasi untuk: '{query_text}'")

    # 1. Transformasi query pengguna menjadi vektor TF-IDF
    query_vec = tfidf_vectorizer.transform([query_text])

    # 2. Hitung cosine similarity antara vektor query dengan seluruh matriks dokumen
    # .flatten() digunakan untuk mengubah matriks 2D menjadi array 1D
    sim_scores = cosine_similarity(query_vec, tfidf_matrix).flatten()

    # 3. Dapatkan indeks dokumen dengan skor tertinggi
    # argsort() mengurutkan dari terkecil ke terbesar, jadi kita ambil N-terakhir dan balik urutannya [::-1]
    top_indices = sim_scores.argsort()[::-1][:top_n]

    # 4. Filter hasil rekomendasi yang skornya > 0 (jika 0 berarti tidak ada kata yang cocok sama sekali)
    valid_indices = [idx for idx in top_indices if sim_scores[idx] > 0]

    if not valid_indices:
        return "Tidak ditemukan artikel yang mengandung kata kunci tersebut secara leksikal."

    # 5. Ekstrak data dari dataframe
    hasil = df_preprocessed.iloc[valid_indices][['title', 'authors', 'categories', 'abstract', 'year']]

    # Tambahkan skor kemiripan untuk dianalisis
    hasil['cosine_score'] = sim_scores[valid_indices]

    return hasil

"""Mengimplementasi function get_recommendations_by_query untuk mendapatkan rekomendasi berdasarkan query yang dimasukkan"""

hasil_rekomendasi = get_recommendations_by_query('mathematical theory of deep learning', top_n=5)
hasil_rekomendasi

"""Mengimplementasi function get_recommendations_by_query ulang dengan query yang berbeda"""

query = 'mathematical theory of deep learning'
print(f"Mencari rekomendasi untuk: '{query}'")
hasil_rekomendasi_tfidf = get_recommendations_tfidf(query, top_n=5)
hasil_rekomendasi_tfidf

"""# **Evaluasi Sistem Rekomendasi**
Memanfaatkan nilai jacard simmilarity dan cosine simmilarity untuk mengevaluasi performa dari sistem rekomendasi berdasarkan kesamaan kata dan jarak nya

## **Function Section Untuk Evaluasi Sistem Rekomendasi**
"""

def hitung_jaccard(teks1, teks2):
    """
    Menghitung Jaccard Similarity (irisan kata) antara dua teks.
    Kata-kata pendek (panjang < 4) diabaikan agar fokus pada kata kunci (keyword).
    """
    # Memecah teks menjadi himpunan (set) kata-kata unik
    set1 = set([kata for kata in str(teks1).lower().split() if len(kata) > 3])
    set2 = set([kata for kata in str(teks2).lower().split() if len(kata) > 3])

    irisan = len(set1.intersection(set2))
    gabungan = len(set1.union(set2))

    return irisan / gabungan if gabungan != 0 else 0

def evaluate_recommender_system(top_k=5, sample_size=100):
    """
    Mengevaluasi performa sistem rekomendasi berdasarkan
    Cosine Similarity (Semantik) dan Jaccard Similarity (Leksikal).
    """
    print(f"Evaluasi Dual-Metric pada {sample_size} artikel acak (Top-{top_k})")

    # Ambil sampel indeks acak dari dataset
    np.random.seed(42) # Seed agar hasil konsisten saat di-run ulang
    sample_indices = np.random.choice(df_preprocessed.index, size=sample_size, replace=False)

    total_cosine_sim = 0
    total_jaccard_sim = 0

    for idx in sample_indices:
        # Teks abstrak asli (sebagai Ground Truth leksikal)
        abstrak_asli = df_preprocessed.iloc[idx]['abstract']

        # Ambil vektor target
        target_vector = embeddings[idx].reshape(1, -1)

        # Cari tetangga terdekat
        # Ambil top_k + 1 karena hasil indeks ke-0 selalu artikel itu sendiri (distance = 0)
        distances, indices = nn_model.kneighbors(target_vector, n_neighbors=top_k + 1)

        # Buang artikel itu sendiri dari hasil pencarian
        recommended_distances = distances[0][1:]
        recommended_indices = indices[0][1:]

        cosine_akumulasi = 0
        jaccard_akumulasi = 0

        for i, rec_idx in enumerate(recommended_indices):
            # 1. Hitung Cosine Similarity
            # KNN mengembalikan jarak (Distance). Similarity = 1 - Distance
            cosine_sim = 1 - recommended_distances[i]
            cosine_akumulasi += cosine_sim

            # 2. Hitung Jaccard Similarity
            abstrak_rekomendasi = df_preprocessed.iloc[rec_idx]['abstract']
            jaccard_sim = hitung_jaccard(abstrak_asli, abstrak_rekomendasi)
            jaccard_akumulasi += jaccard_sim

        # Rata-ratakan skor untuk 1 artikel query ini
        total_cosine_sim += (cosine_akumulasi / top_k)
        total_jaccard_sim += (jaccard_akumulasi / top_k)

    # Hitung rata-rata akhir dari seluruh sampel pengujian
    avg_cosine_similarity = (total_cosine_sim / sample_size) * 100
    avg_jaccard_similarity = (total_jaccard_sim / sample_size) * 100

    print(f"1. Rata-rata Cosine Similarity : {avg_cosine_similarity:.2f}%")
    # print(f"   (Skor di atas 70% membuktikan rekomendasi sangat relevan secara konteks/makna)")
    print(f"2. Rata-rata Jaccard Similarity: {avg_jaccard_similarity:.2f}%")
    # print(f"   (Skor 10% - 30% membuktikan model merekomendasikan artikel dengan kata yang bervariasi, tidak sekadar copy-paste)")

def evaluate_tfidf_system(top_k=5, sample_size=100):
    print(f"Evaluasi TF-IDF pada {sample_size} artikel acak (Top-{top_k})")

    # Gunakan seed 42 agar hasil acaknya sama persis dengan evaluasi Deep Learning
    np.random.seed(42)
    sample_indices = np.random.choice(df_preprocessed.index, size=sample_size, replace=False)

    total_cosine_sim = 0
    total_jaccard_sim = 0
    valid_samples = 0 # Menghitung berapa sampel yang sukses dapat rekomendasi

    for idx in sample_indices:
        # Gunakan teks abstrak dari dataset sebagai kueri pencarian (query_text)
        abstrak_asli = df_preprocessed.iloc[idx]['abstract']

        # Panggil fungsi rekomendasimu (minta top_k + 1 karena hasil pertama pasti artikel itu sendiri)
        hasil_df = get_recommendations_tfidf(abstrak_asli, top_n=top_k + 1)

        # Jika hasil mengembalikan pesan string (tidak ada kecocokan), lewati sampel ini
        if isinstance(hasil_df, str):
            continue

        # Karena fungsi milikmu mengembalikan DataFrame dari df_preprocessed.iloc,
        # index aslinya masih menempel! Kita bisa membuang artikel itu sendiri dengan mudah:
        hasil_df = hasil_df[hasil_df.index != idx].head(top_k)

        if len(hasil_df) == 0:
            continue

        valid_samples += 1

        # 1. Hitung rata-rata Cosine Similarity dari kolom hasil_df
        # Karena nilai di dalam kolom sudah berupa kemiripan (0.0 - 1.0), tinggal dirata-rata
        cosine_akumulasi = hasil_df['cosine_score'].sum()

        # 2. Hitung Jaccard Similarity (Looping ke setiap abstrak yang direkomendasikan)
        jaccard_akumulasi = 0
        for _, row in hasil_df.iterrows():
            abstrak_rekomendasi = row['abstract']
            jaccard_sim = hitung_jaccard(abstrak_asli, abstrak_rekomendasi)
            jaccard_akumulasi += jaccard_sim

        total_cosine_sim += (cosine_akumulasi / len(hasil_df))
        total_jaccard_sim += (jaccard_akumulasi / len(hasil_df))

    # Kalkulasi nilai akhir
    avg_cosine = (total_cosine_sim / valid_samples) * 100 if valid_samples > 0 else 0
    avg_jaccard = (total_jaccard_sim / valid_samples) * 100 if valid_samples > 0 else 0

    print(f"1. Rata-rata Cosine Similarity (TF-IDF): {avg_cosine:.2f}%")
    # print(f"   (Catatan: TF-IDF mengukur kemiripan kosa kata persis/Exact Match)")
    print(f"2. Rata-rata Jaccard Similarity        : {avg_jaccard:.2f}%")
    # print(f"*(Berhasil dievaluasi dari {valid_samples} sampel yang memiliki rekomendasi)*")

"""Mengimplementasikan procedure evaluate_recommender_system untuk mengevaluasi performa dari sistem rekomendasi"""

evaluate_recommender_system(top_k=5, sample_size=100)

evaluate_tfidf_system(top_k=5, sample_size=100)