# -*- coding: utf-8 -*-
"""Submission 1 - MLT - Muhammad Faris Akbar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mczy8E4ebc0R73T7MEgy6ZsqjXxTzCiX

# **Load Library Yang Akan digunakan**
"""

import pandas as pd
import os
import kagglehub
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

from sklearn.utils import resample
from scipy.stats import iqr
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb

"""# **Load Dataset Dari Kaggle ([Dataset Link](https://www.kaggle.com/datasets/laveshjadon/ai-impact-on-students/data))**

## **Deskripsi Kolom**
**Column-Type-Description**
1. Student_ID-Integer-Unique numeric identifier for each student (100001–150000)

2. Major_Category-Categorical-Student's field of study — STEM, Business, Humanities, Medical, Arts
3. Year_of_Study-Categorical-Academic standing — Freshman, Sophomore, Junior, Senior, Graduate
4. Pre_Semester_GPA-Float-GPA at the start of the semester (range: ~1.18 – 4.00)
5. Post_Semester_GPA-Float-GPA at the end of the semester (range: ~1.00 – 4.00) — primary outcome variable

6. Weekly_GenAI_Hours-Float-Average hours per week spent using Generative AI tools (0 – 40 hrs)
7. Primary_Use_Case-Categorical-Main purpose for which the student uses AI — Copywriting/Drafting, Summarizing_Reading, Debugging/Troubleshooting, Ideation, Direct_Answer_Generation
8. Prompt_Engineering_Skill-Categorical-Self-assessed proficiency in crafting effective prompts — Beginner, Intermediate, Advanced
9. Tool_Diversity-Integer-Number of distinct AI tools used (1–5)
10. Paid_Subscription-Boolean-Whether the student has a paid AI subscription (True / False)

11. Traditional_Study_Hours-Float-Weekly hours devoted to traditional (non-AI) study methods (1 – ~36 hrs)
12. Perceived_AI_Dependency-Integer-Student's self-rated dependency on AI tools, on a scale of 1 (low) to 10 (high)

13. Institutional_Policy-Categorical-The institution's official stance on AI usage — Allowed_With_Citation, Strictly_Ban, Actively_Encouraged

14. Anxiety_Level_During_Exams-Integer-Self-reported exam anxiety score from 1 (minimal) to 10 (severe)
15. Skill_Retention_Score-Float-Score (0–100) measuring how well students retained learned skills post-semester
16. Burnout_Risk_Level-Categorical-Assessed burnout risk — Low, Medium, High

## **Target Variable**
**Analisis-Kolom**
*   Regression-Post_Semester_GPA, Skill_Retention_Score
*   Classification-Burnout_Risk_Level
*   Analysis-Perceived_AI_Dependency, Anxiety_Level_During_Exams
"""

# Download latest version
path = kagglehub.dataset_download("laveshjadon/ai-impact-on-students")

print("Path to dataset files:", path)

"""## **Cek Nama File Di Folder**"""

for file in os.listdir(path):
    print(file)

data = pd.read_csv(os.path.join(path, "ai_student_impact_dataset (1).csv"))

"""## **5 Kolom Teratas dan Terbawah**"""

data.head(5)

data.tail(5)

"""# **Simple EDA Untuk Penentuan Metode Pre-Processing**

## **Cek Informasi Dataset**
"""

data.info()

data.describe()

"""Dikarenakan Student_ID merupakan identifier data, maka kolom ini akan dihapus untuk mempermudah analisis"""

data.drop('Student_ID', axis=1, inplace=True)
data.head(5)

def cek_nan(data):
  """
  Function yang digunakan untuk memeriksa nilai nan dari data
  input   : data
  output  : nan_info (DataFrame)
  return  : nan_info (DataFrame)
  """
  nan_info = pd.DataFrame(data.isna().sum().sort_values(ascending=False), columns=['Jumlah Nilai Missing'])

  if nan_info['Jumlah Nilai Missing'].sum() == 0:
    print("Tidak ada nilai missing")
    return None
  else:
    nan_info['Persentase Nilai Missing (%)'] = ((nan_info['Jumlah Nilai Missing'] / len(data)) * 100).round(3)

    # return data dengan nilai missing, apabila ingin mereturn keseluruhan data maka ubah menjadi return nan_info
    return nan_info[nan_info['Jumlah Nilai Missing'] > 0]


def visualize_row_with_nan(data, method='all', columns=None):
  """
  Procedure yang digunakan untuk menvisualisasikan baris yang mengandung NaN berdasarkan metode yang dipilih
  input   : data, method, columns
  output  : baris_nan (DataFrame)
  """
  try:
    if method not in ['all', 'column', 'columns']:
      raise ValueError("Metode tidak valid. Pilih salah satu dari 'all', 'column', 'columns'.")

    if method == 'all':
      display(data[data.isna().any(axis=1)])

    elif method == 'column':
      if not isinstance(columns, str):
          raise TypeError("Untuk metode 'column', argumen 'columns' harus berupa String.")
      if columns not in data.columns:
          raise KeyError(f"Kolom '{columns}' tidak ditemukan dalam DataFrame.")
      display(data[data[columns].isna()])

    elif method == 'columns':
      if not isinstance(columns, list):
          raise TypeError("Untuk metode 'columns', argumen 'columns' harus berupa list.")
      for column in columns:
          if column not in data.columns:
              raise KeyError(f"Kolom '{column}' tidak ditemukan dalam DataFrame.")
      display(data[data[columns].isna().all(axis=1)])

  except (TypeError, KeyError) as e:
    print(f"Kesalahan dalam memproses data: {e}")


def visualize_row_with_duplicated(data):
  """
  Procedure yang digunakan untuk menvisualisasikan baris yang mengandung data duplikat
  input   : data
  output  : baris_duplikat (DataFrame)
  """
  duplicated = data.duplicated().sum()

  if duplicated > 0:
    print("Jumlah Data Duplikat :", duplicated)
    all_duplicates = data[data.duplicated(keep=False)]

    duplicate_indices = all_duplicates.groupby(list(all_duplicates.columns)).groups
    print("Pasangan Data Duplikat :")
    for group_indices in duplicate_indices.values():
      if len(group_indices) > 1:
        display(data.iloc[list(group_indices)])
        print("\n")
  else:
    print("Tidak ada data duplikat")


def get_bounds(data):
  """
  Function helper yang digunakan untuk mendapatkan batas bawah dan batas atas dari data
  input   : data
  output  : lower, upper
  return  : lower, upper
  """
  q1 = data.quantile(0.25)
  q3 = data.quantile(0.75)
  # nan_policy omit digunakan untuk ignore nilai NaN, sehingga perhitungan outlier tidak terganggu oleh nilai NaN
  IQR = iqr(data, nan_policy='omit')

  lower = q1 - 1.5 * IQR
  upper = q3 + 1.5 * IQR

  return lower, upper


def get_outlier(data, lower, upper, columns=None):
  """
  Function helper untuk mendapatkan outlier dari data
  input   : data, lower, upper, columns
  output  : outliers (DataFrame)
  return  : outliers (DataFrame)
  """
  return data[(data[columns] < lower) | (data[columns] > upper)]


def cek_outlier_iqr(data, method='all', columns=None):
  """
  Procedure untuk memeriksa outlier menggunakan metode IQR
  input   : data, method, columns
  output  : outliers (DataFrame)
  """
  try:
    if method not in ['all', 'column', 'columns']:
      raise ValueError("Metode tidak valid. Pilih salah satu dari 'all', 'column', 'columns'.")

    if method == 'all':
      for column in data.select_dtypes(include=np.number).columns:
        lower, upper = get_bounds(data[column])
        outliers = get_outlier(data, lower, upper, column)

        if not outliers.empty:
          print(f"Outliers pada kolom {column}:")
          display(outliers[column])
          print("\n")

      if outliers.empty:
        print(f"Tidak ada outlier pada data")

    elif method == 'column':
      if not isinstance(columns, str):
        raise TypeError("Untuk metode 'column', argumen 'columns' harus berupa String.")
      if columns not in data.columns:
        raise KeyError(f"Kolom '{columns}' tidak ditemukan dalam DataFrame.")
      if not np.issubdtype(data[columns].dtype, np.number):
        raise TypeError(f"Kolom '{columns}' bukan tipe numerik.")
      lower, upper = get_bounds(data[columns])
      outliers = get_outlier(data, lower, upper, columns)

      if not outliers.empty:
        print(f"Outliers pada kolom {columns}:")
        display(outliers[column])
      else:
        print(f"Tidak ada outlier pada kolom {columns}")

    elif method == 'columns':
      if not isinstance(columns, list):
        raise TypeError("Untuk metode 'columns', argumen 'columns' harus berupa list.")
      for column in columns:
        if column not in data.columns:
          raise KeyError(f"Kolom '{column}' tidak ditemukan dalam DataFrame.")
        if not np.issubdtype(data[column].dtype, np.number):
          raise TypeError(f"Kolom '{column}' bukan tipe numerik.")

        lower, upper = get_bounds(data[column])
        outliers = get_outlier(data, lower, upper, column)

        if not outliers.empty:
          print(f"Outliers pada kolom {column}:")
          display(outliers[column])
          print("\n")
        else:
          print(f"Tidak ada outlier pada kolom {column}")

  except (TypeError, KeyError) as e:
    print(f"Kesalahan dalam memproses data: {e}")


def filter_outlier_method(data, lower, upper, method='capping', column=None):
  """
  Function helper untuk menfilter data berdasarkan batas bawah dan batas atas
  input   : data, lower, upper, method, columns
  output  : filtered_data (DataFrame)
  return  : filtered_data (DataFrame)
  """
  if method == "nan":  # ubah outlier → NaN
    data.loc[(data[column] < lower) | (data[column] > upper), column] = np.nan
  elif method == "drop":  # hapus baris dengan outlier
    data = data[(data[column] >= lower) & (data[column] <= upper)]
  elif method == "capping":
    data.loc[data[column] < lower, column] = lower
    data.loc[data[column] > upper, column] = upper

  return data


def filter_outliers_iqr(data, filter_method="capping", column_method="all", columns=None):
  """
  Procedure untuk menfilter outlier menggunakan metode IQR
  input   : data, filter_method, column_method, columns
  output  : filtered data (DataFrame)
  return  : filtered data (DataFrame)
  """
  try:
    if filter_method not in ['nan', 'drop', 'capping']:
      raise ValueError("Metode tidak valid. Pilih salah satu dari 'nan', 'drop', 'capping'.")
    if column_method not in ['all', 'column', 'columns']:
      raise ValueError("Metode tidak valid. Pilih salah satu dari 'all', 'column', 'columns'.")

    if column_method == 'all':
      for column in data.select_dtypes(include=np.number).columns:
        lower, upper = get_bounds(data[column])
        data = filter_outlier_method(data, lower, upper, filter_method, column)

    if column_method == 'column':
      if not isinstance(columns, str):
          raise TypeError("Untuk metode 'column', argumen 'columns' harus berupa String.")
      if columns not in data.columns:
          raise KeyError(f"Kolom '{columns}' tidak ditemukan dalam DataFrame.")
      if not np.issubdtype(data[columns].dtype, np.number):
          raise TypeError(f"Kolom '{columns}' bukan tipe numerik.")

      lower, upper = get_bounds(data[columns])
      data = filter_outlier_method(data, lower, upper, filter_method, column)

    if column_method == 'columns':
      if not isinstance(columns, list):
        raise TypeError("Untuk metode 'columns', argumen 'columns' harus berupa list.")
      for column in columns:
        if column not in data.columns:
          raise KeyError(f"Kolom '{column}' tidak ditemukan dalam DataFrame.")
        if not np.issubdtype(data[column].dtype, np.number):
          raise TypeError(f"Kolom '{column}' bukan tipe numerik.")

        lower, upper = get_bounds(data[column])
        data = filter_outlier_method(data, lower, upper, filter_method, column)

  except (ValueError) as e:
    print(f"Kesalahan dalam memproses data: {e}")
  return data

"""## **Cek Nilai NaN**"""

cek_nan(data)

"""## **Cek Nilai Duplikat**"""

visualize_row_with_duplicated(data)

"""## **Cek Outlier**"""

cek_outlier_iqr(data)

"""## **Visualisasi Persebaran Data Untuk Melihat Data Yang Diduga Outlier**"""

col = 3
row = math.ceil(data.shape[1] / col)

plt.figure(figsize=(15, 15))

for i, column in enumerate(data.select_dtypes(include=np.number).columns, 1):
  plt.subplot(row, col, i)
  sns.histplot(data[column], kde=True)
  plt.title(column)
  plt.xlabel(column)
  plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 15))

for i, column in enumerate(data.select_dtypes(include=np.number).columns, 1):
  plt.subplot(row, col, i)
  sns.violinplot(data[column], inner=None)
  sns.boxplot(data[column], width=0.15, color='white', linewidth=1, fliersize=4)
  plt.title(column)
  plt.xlabel(column)
  plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""Walaupun ditemukan adanya outlier melalui pemeriksaan IQR, ditemukan bahwa nilai tersebut masih termasuk dalam batas normal didalam range yang ditentukan, sehingga nilai yang diduga outlier tersebut tetap akan dipertahankan.

# **EDA Lanjutan Untuk Analisis Mendalam**

## **Distribusi Burnout Level**
"""

plt.figure(figsize=(8, 8))
ax = sns.countplot(data=data, x='Burnout_Risk_Level', order=['Low', 'Medium', 'High'], palette='viridis')
plt.title('Distribusi Risiko Burnout Mahasiswa')
plt.xlabel('Tingkat Risiko Burnout')
plt.ylabel('Jumlah Mahasiswa')
plt.bar_label(ax.containers[0])
plt.bar_label(ax.containers[1])
plt.bar_label(ax.containers[2])
plt.show()

"""Dari sisi tingkat risiko burnout, ditemukan bahwa tingkat burnout tertinggi terdapat pada tingkat medium. Untuk mengetahui lebih lanjut variable mana yang paling mempengaruhi tingkat burnout, akan dilakukan analisis plot per masing-masing kolom.

## **Visualisasi Tren dengan Point Plot**
"""

col = 3
row = math.ceil(data.shape[1] / col)

plt.figure(figsize=(15, 15))

for i, column in enumerate(data.select_dtypes(include=np.number).columns, 1):
  plt.subplot(row, col, i)
  sns.pointplot(data=data, x='Burnout_Risk_Level', y=column, order=['Low', 'Medium', 'High'], color='teal')
  plt.title(f'Tren {column} vs Burnout Risk')
  plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

"""Berdasarkan visualisasi tren tersebut, ditemukan beberapa informasi menarik dari data.
1. Tingkatan sering menggunakan AI per minggu, semakin tinggi tingkat anxiety ketika ujian dan semakin ketergantungan seseorang terhadap AI, maka semakin tinggi pula tingkatan burnout nya.
2. Semakin tinggi jumlah jam belajar tradisional seseorang, maka semakin rendah tingkatan burnout nya.
3. Semakin banyak jumlah tools AI yang digunakan, maka semakin tinggi pula tingkatan burnout nya.
4. Semakin tinggi nilai keterampilan pembelajaran siswa sampai akhir semester, maka tingkatan burnout nya menjadi semakin rendah.

# **Processing Data**

## **Cek Informasi Data Yang Akan Dilakukan Encoding**
"""

data.info()

data_object_boolean = data.select_dtypes(include=['object', 'bool'])
data_object_boolean.head(5)

"""## **Encoding Fitur Kategorikal**"""

le_target = LabelEncoder()
data['Burnout_Risk_Level'] = le_target.fit_transform(data['Burnout_Risk_Level'])

prompt_mapping = {'Beginner': 0, 'Intermediate': 1, 'Advanced': 2}

data['Prompt_Engineering_Skill'] = data['Prompt_Engineering_Skill'].map(prompt_mapping)

Year_of_Study_mapping = {'Freshman':1, 'Sophomore':2, 'Junior':3, 'Senior':4, 'Graduate':5}

data['Year_of_Study'] = data['Year_of_Study'].map(Year_of_Study_mapping)

data['Paid_Subscription'] = data['Paid_Subscription'].astype(int)

data = pd.get_dummies(data)

bool_cols = data.select_dtypes(include=['bool']).columns
data[bool_cols] = data[bool_cols].astype(int)

data.head(5)

"""## **Feature Engineering**"""

data['gpa_difference'] = data['Post_Semester_GPA'] - data['Pre_Semester_GPA']
data['hours_per_week'] = data['Weekly_GenAI_Hours'] + data['Traditional_Study_Hours']

"""## **Analisis Korelasi Untuk Menentukan Fitur Yang Akan Digunakan**"""

corr = data.corr(method='spearman')
plt.figure(figsize=(25, 25))
sns.heatmap(corr, annot=True)
plt.title('Korelasi Fitur Numerik')
plt.show()

corr_stacked = corr.unstack()
corr_stacked = corr_stacked[corr_stacked != 1.0]
target_corr = corr_stacked[abs(corr_stacked) > 0.8].drop_duplicates()

print("Pasangan variabel dengan korelasi > 0.8:")
print(target_corr)

"""Kolom memiliki nilai korelasi yang kuat diatas 0.9 kemungkinan akan memiliki redudansi informasi. Cara penanganan nya adalah salah satu kolom yang kurang memiliki korelasi dengan target akan dihapus."""

corr_target = data.corr(method='spearman')
corr_target = corr_target[['Burnout_Risk_Level']].sort_values(by='Burnout_Risk_Level', ascending=False)
plt.figure(figsize=(15, 15))
sns.heatmap(corr_target, annot=True, cmap='coolwarm', cbar=True)
plt.title('Korelasi Fitur terhadap Burnout Risk Level')
plt.show()

data.drop(['Pre_Semester_GPA'], axis=1, inplace=True)

corr_target = data.corr(method='spearman')
corr_target = corr_target[['Burnout_Risk_Level']].sort_values(by='Burnout_Risk_Level', ascending=False)
plt.figure(figsize=(15, 15))
sns.heatmap(corr_target, annot=True, cmap='coolwarm', cbar=True)
plt.title('Korelasi Fitur terhadap Burnout Risk Level')
plt.show()

"""## **Filter Kolom Yang Memiliki Korelasi Positif Dengan Target**"""

top_15_kolom_target = corr_target.head(15).index
top_15_kolom_target

data_selected = data[top_15_kolom_target]
data_selected

"""## **Resampling Data**"""

# 0: High, 1: Low, 2: Medium
data_selected_0 = data_selected[data_selected['Burnout_Risk_Level'] == 0]
data_selected_1 = data_selected[data_selected['Burnout_Risk_Level'] == 1]
data_selected_2 = data_selected[data_selected['Burnout_Risk_Level'] == 2]

n_samples = len(data_selected_2)

data_selected_0_upsampling = resample(data_selected_0, replace=True, n_samples=n_samples, random_state=42)
data_selected_1_upsampling = resample(data_selected_1, replace=True, n_samples=n_samples, random_state=42)

data_selected_balanced = pd.concat([data_selected_2, data_selected_1_upsampling, data_selected_0_upsampling])

"""Upsampling data agar memiliki jumlah target yang serupa, sehingga tidak terjadi prediksi kelas dominan."""

plt.figure(figsize=(8, 8))
ax = sns.countplot(data=data_selected_balanced, x='Burnout_Risk_Level', palette='viridis')
plt.title('Distribusi Risiko Burnout Mahasiswa')
plt.xlabel('Tingkat Risiko Burnout')
plt.ylabel('Jumlah Mahasiswa')
plt.bar_label(ax.containers[0])
plt.bar_label(ax.containers[1])
plt.bar_label(ax.containers[2])
plt.show()

"""## **Splitting Data**"""

X = data_selected_balanced.drop('Burnout_Risk_Level', axis=1)
y = data_selected_balanced['Burnout_Risk_Level']

X.head(5)

y.head(5)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""## **Standarisasi Data**"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""# **Modelling**"""

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print(f"Akurasi Random Forest: {accuracy_score(y_test, rf_pred):.4f}")

xgb_model = xgb.XGBClassifier(eval_metric='mlogloss', random_state=42)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)
print(f"Akurasi XGBoost: {accuracy_score(y_test, xgb_pred):.4f}")

"""# **Evaluasi Model**"""

print("=== Laporan Evaluasi XGBoost ===")
print(f"Akurasi Akhir: {accuracy_score(y_test, xgb_pred):.4f}\n")
print(classification_report(y_test, xgb_pred, target_names=le_target.classes_))

# Visualisasi Confusion Matrix untuk model
plt.figure(figsize=(7,5))
sns.heatmap(confusion_matrix(y_test, xgb_pred), annot=True, fmt='d', cmap='Blues',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title('Confusion Matrix - Model XGBoost')
plt.xlabel('Tebakan Model (Predicted)')
plt.ylabel('Fakta Sebenarnya (Actual)')
plt.show()

print("=== Laporan Evaluasi Random Forest ===")
print(f"Akurasi Akhir: {accuracy_score(y_test, rf_pred):.4f}\n")
print(classification_report(y_test, rf_pred, target_names=le_target.classes_))

# Visualisasi Confusion Matrix untuk model
plt.figure(figsize=(7,5))
sns.heatmap(confusion_matrix(y_test, rf_pred), annot=True, fmt='d', cmap='Blues',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title('Confusion Matrix - Model Random Forest')
plt.xlabel('Tebakan Model (Predicted)')
plt.ylabel('Fakta Sebenarnya (Actual)')
plt.show()

"""# **Hyperparameter Tuning**"""

param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'n_estimators': [100, 200]
}

grid_search = GridSearchCV(
    estimator=xgb.XGBClassifier(eval_metric='mlogloss', random_state=42),
    param_grid=param_grid,
    scoring='accuracy',
    cv=3,
    verbose=0
)

grid_search.fit(X_train, y_train)
print(f"Parameter Terbaik Ditemukan: {grid_search.best_params_}")

best_xgb_model = grid_search.best_estimator_
best_xgb_pred = best_xgb_model.predict(X_test)

param_grid = {
    'max_depth': [3, 5, 7],
    'n_estimators': [100, 200],
    'min_samples_split': [2, 5]
}

grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    scoring='accuracy',
    cv=3,
    verbose=0
)

grid_search.fit(X_train, y_train)
print(f"Parameter Terbaik Ditemukan: {grid_search.best_params_}")

best_rf_model = grid_search.best_estimator_
best_rf_pred = best_rf_model.predict(X_test)

"""# **Evaluasi Model Tuning**"""

print("=== Laporan Evaluasi Final (XGBoost Tuned) ===")
print(f"Akurasi Akhir: {accuracy_score(y_test, best_xgb_pred):.4f}\n")
print(classification_report(y_test, best_xgb_pred, target_names=le_target.classes_))

# Visualisasi Confusion Matrix untuk model final
plt.figure(figsize=(7,5))
sns.heatmap(confusion_matrix(y_test, best_xgb_pred), annot=True, fmt='d', cmap='Blues',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title('Confusion Matrix - Model XGBoost Final')
plt.xlabel('Tebakan Model (Predicted)')
plt.ylabel('Fakta Sebenarnya (Actual)')
plt.show()

print("=== Laporan Evaluasi Final (Random Forest Tuned) ===")
print(f"Akurasi Akhir: {accuracy_score(y_test, best_rf_pred):.4f}\n")
print(classification_report(y_test, best_rf_pred, target_names=le_target.classes_))

# Visualisasi Confusion Matrix untuk model final
plt.figure(figsize=(7,5))
sns.heatmap(confusion_matrix(y_test, best_rf_pred), annot=True, fmt='d', cmap='Blues',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title('Confusion Matrix - Model Random Forest Final')
plt.xlabel('Tebakan Model (Predicted)')
plt.ylabel('Fakta Sebenarnya (Actual)')
plt.show()